import type { Metadata } from "next";
import { Roboto } from 'next/font/google'
import Header from "app/components/shared/Header/Header";
import Footer from "app/components/shared/Footer/Footer";
import 'app/sass/globals.sass';

const roboto = Roboto({
  weight: ["100", "300","500", "700"],
  subsets: ["latin"],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
